# Generated by Django 4.0.3 on 2022-04-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parte3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comics',
            name='onsaleDate',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
    ]
