# Generated by Django 4.0.3 on 2022-04-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parte2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios_atlas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('edad', models.IntegerField(blank=True)),
                ('token', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='autoridad',
        ),
    ]
