# Generated by Django 4.0.3 on 2022-04-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parte2', '0002_usuarios_atlas_delete_autoridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios_atlas',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuarios_atlas',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios_atlas',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
