# Generated by Django 4.0.3 on 2022-04-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parte2', '0003_alter_usuarios_atlas_edad_alter_usuarios_atlas_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios_atlas',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios_atlas',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
